# Generated by Django 3.1.1 on 2020-11-19 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201117_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 19, 21, 57, 890206)),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 19, 21, 57, 890206)),
        ),
    ]
