# Generated by Django 3.1.1 on 2020-11-19 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201119_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 23, 44, 3, 602802)),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 23, 44, 3, 601807)),
        ),
    ]
