# Generated by Django 3.1.1 on 2020-11-21 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201119_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 15, 31, 50, 18887)),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 15, 31, 50, 17831)),
        ),
    ]
