# Generated by Django 3.1.1 on 2020-11-21 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201121_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 15, 38, 32, 664020)),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 15, 38, 32, 662818)),
        ),
    ]
