# Generated by Django 3.1.1 on 2020-11-21 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201121_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 1, 41, 7, 551183)),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 1, 41, 7, 549104)),
        ),
    ]
