# Generated by Django 3.1.1 on 2020-11-22 17:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20201122_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='blogger',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blogger', to='blog.blogger'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 23, 19, 27, 276879)),
        ),
        migrations.AlterField(
            model_name='followers',
            name='follower',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='blog.blogger'),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 23, 19, 27, 276843)),
        ),
    ]
