# Generated by Django 3.1.1 on 2020-12-11 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20201122_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='blogger',
        ),
        migrations.RemoveField(
            model_name='followers',
            name='follower',
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 11, 20, 24, 894771)),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
